### ISSUE TITLE
decrypt함수의 encoding issue

### ISSUE THREAD

**Issue by kr-yeon** [predict-woo/kisa-seed#1]
안녕하세요.
해당 라이브러리를 잘 보았습니다.
우선 라이브러리 제작에 감사합니다.

해당 라이브러리 사용중, Uint8Array를 utf8로 변환해서 decrypted data를 전달해주는 부분에, utf8로 인한 데이터 변형에 대해 issue를 남깁니다.

현재 해당 라이브러리로 테스트중, 마지막 decrypt함수에서 Uint8Array를 utf8 string으로 변환하는 부분에, 가지고 있는 데이터가 깨지는 issue가 발생했습니다.

해당 모듈에서 Uint8Array를 원형 그대로 반환하여, Buffer로 변환해 사용한 경우에는 문제가 없었습니다.

혹 해당 issue에 관해 같이 이야기 나누실 수 있으실까요?

**Comment by kr-yeon** [comment]
제 의견은 현재 모든 input과 encoding의 output은 base64로 분석되었는데, 혹 해당 형태로 IO를 맞춰서 작업하는건 어떨까 싶어 문의를 남깁니다.

Input과 Output에 대한 일관성을 가질 수 있고, base64로 변환시 원형태의 데이터가 유지되는것을 발견했습니다.

**Comment by kr-yeon** [comment]
해당 부분에 대한 수정사항이 반영된 #2 PR작성하였습니다.

**Comment by predict-woo** [comment]
@kr-yeon 안녕하세요! 이슈 만들어주셔서 감사합니다 :) 이미 포크를 떠서 해결하신 것 같지만 아직 관심이 있으실까 해서 적어봅니다.

일단 말씀해주신 문제는 해결해보고 싶어서 데이터가 깨지는 예시를 전달해주실 수 있다면 정말 감사하겠습니다

추가적으로 제 개인적인 의견으로는 encrypt / decrypt 함수는 대칭적인게 맞다고 생각합니다.
예를 들어 `decrypt(encrypt(string))`을 하면 원본 `string`이 나오는게 바람직 한 것 같습니다.

제가 잘못 이해하고 있을 수도 있지만, 올려주신 pr을 살펴보면 이 조건을 만족하지 않는 것 같습니다.

일단 버그가 수정되지 않은 현재 상황에서는 조금 더 상위 메서드인 `SEED_CBC_Decrypt`나 `SEED_CBC_Encrypt`를 사용해서 직접encoding / decoding을 구현하는 것을 추천드립니다.

**Comment by kr-yeon** [comment]
넵, 답변 감사드립니다.

깨지는 데이터의 경우, 공인인증서로 테스트하였습니다!
법인 공인인증서로 테스트 하여, 별도로 데이터를 전달드리지 못하는점 양해 부탁드립니다 ㅜ

**Comment by predict-woo** [comment]
넵 감사합니다 :)

**Comment by predict-woo** [comment]
@kr-yeon 안녕하세요! 늦었지만 이 이슈에 대한 수정이 main에 반영되어 다음 릴리스(v1.1.0)에 포함될 예정임을 알려드립니다. (e48734e)

- **`encryptBytes` / `decryptBytes` 메서드 추가** — 키/IV는 기존과 동일하게 base64 문자열을 받고, 평문은 `Uint8Array`로 주고받습니다. 인증서 같은 바이너리 데이터도 변형 없이 그대로 왕복되는 것을 테스트로 확인했습니다.
- **`decrypt`의 동작 변경** — UTF-8이 아닌 평문을 만나면 조용히 데이터를 깨뜨리는 대신 `TypeError`를 던지도록 수정했습니다 (`TextDecoder`의 `fatal: true` 옵션 사용). 기존처럼 깨진 데이터를 반환하는 일은 더 이상 없습니다.
- 추가로 `encrypt`에서 약 100KB 이상의 메시지 암호화 시 발생하던 `RangeError: Maximum call stack size exceeded` 버그도 함께 수정했습니다.

자세한 사용법은 README의 "Binary data" 섹션을 참고해주세요. 제보 감사합니다!
